# -*- coding: utf-8 -*-
"""
Created on Sun May 17 17:14:47 2020

@author: bmcma

DESCRIPTION:
    Train an agent to perform the center out reach task in the FetchReach-v1
    open AI gym environmnet
"""

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import gym
import matplotlib.pyplot as plt
import scipy.io as sio
import pdb
import time
import copy

# comment line below if you are running without cuda
#device = torch.device("cuda")
device = torch.device('cpu')

def InitializeLayer(layerData):
    '''
    
    '''
    layerData.weight.data = torch.randn_like(layerData.weight.data)

class valueNet(nn.Module):
    
    def __init__(self):
        super(valueNet, self).__init__()
        self.fc1 = nn.Linear(16, 8)
        self.fc2 = nn.Linear(8, 4)
        self.fc3 = nn.Linear(4, 1)
        # variance of gaussian from which we draw actions; treated as hyper-parameter
        self.var = 1
        
    def forward(self, x):
        # flatten the state into a vector (16,)
        #x = np.hstack((state['observation'], state['achieved_goal'], state['desired_goal']))
        # place state vector into a torch tensor
        x = torch.from_numpy(x).to(device)
        x = x.float()
        if len(x.shape) == 1:
            x = x.unsqueeze(0)
        # shape into a torch column vector
        x = x.view(-1, self.num_flat_features(x))
        # forward pass 
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        #value = x.cpu().detach().numpy().reshape(1)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

class policyNet(nn.Module):
    
    def __init__(self):
        super(policyNet, self).__init__()
        self.fc1 = nn.Linear(16, 8)
        self.fc2 = nn.Linear(8, 8)
        self.fc3 = nn.Linear(8, 4)
        # variance of gaussian from which we draw actions; treated as hyper-parameter
        self.var = 1
        self.epsilon = 0.1
        
    def forward(self, x):
        # flatten the state into a vector (16,)
        #x = np.hstack((state['observation'], state['achieved_goal'], state['desired_goal']))
        # place state vector into a torch tensor
        x = torch.from_numpy(x).to(device)
        x = x.float()
        if len(x.shape) == 1:
            x = x.unsqueeze(0)
        # shape into a torch column vector
        x = x.view(-1, self.num_flat_features(x))
        # forward pass 
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = torch.tanh(self.fc3(x))
        #action = x.cpu().detach().numpy().reshape(4)
        actionMean = x #+ torch.randn(4, device=device)*self.var
        return actionMean #+ self.var*np.random.randn(4)

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

def  setTargetPosition(env, targetPos=None):
    '''
    DESCRIPTION
    reset the environment to an initial state where the goal target is at one of
    8 target locations. 8 target locations are distributed uniformly around a 
    circle centered on the gripper/hand position. The target position for next 
    episode is drawn uniformly from the 8 allowed target positions. These target 
    positions all exist in a 2D plane to emulate a 2 dimensional human/moneky 
    center out reaching task. 
    
    the origin is located on the bottom left grey corner of the render.
    The table is located at roughly z=0.5
    x goes from roughly x=1 to x=1.5 
    y goes from roughly y = 0.4 to y=1.1
    '''
    # get the starting position of the hand (always the same)
    centerPosition = env.env.initial_gripper_xpos
    scaleFactor = 0.3   
    
    if targetPos is None:
        theta = np.pi*np.random.randint(0, 8)/4
        reachDirection = np.array([np.cos(theta), np.sin(theta), 0])

        # place the target at the random reach position    
        reachTargetPos = centerPosition + scaleFactor * reachDirection
    else:
        reachTargetPos = centerPosition + scaleFactor * targetPos
    # manual place target at desired location
    env.env.goal = reachTargetPos
    return reachTargetPos

def getFeatureVector(observation):
    '''
    DESCRIPTION: takes an observation dictionary from FetchReach-v1 environment
                and converts it into a feature vector to be used in Policy and 
                value networks. 
    Parameters
    ----------
    observation : dictionary obejct generated by calling env.step(action)
    '''
    stateFeatures = np.hstack((observation['observation'], \
                    observation['achieved_goal'], observation['desired_goal']))
    return stateFeatures

def updateValueEstimate(lmbda=0.95):
    '''
    DESCRIPTION: updates the value network parameters using computed TD targets.

    Returns
    -------
    None.

    '''
    pass

def computeTD(sampleTuples, lmbd=0.95, tupleIX=None):
    '''
    DESCRIPTION: computes the TD error for a sampled tuple

    Returns
    -------
    Gt: TD target for a randomly sampled tuple or inputed tuple
    state: feature vector of sampled tuple

    '''
    numTimeSteps = len(sampleTuples)
    # if tupleIX not given, randomly sample a tuple
    if tupleIX is None:
        tupleIX = int( numTimeSteps*np.random.rand() )

    Gt = torch.zeros((1, 1))
    discountedRewards = 0
    for futureTimeStep in range(tupleIX, numTimeSteps):
        n = futureTimeStep - (tupleIX)
        futureReward = sampleTuples[futureTimeStep]['reward']
        discountedRewards += (discountFactor**n) * futureReward
        if ( (futureTimeStep + 1) != numTimeSteps):
            nextState = sampleTuples[futureTimeStep]['next_state']
            valueEstimate = value(nextState)
            #valueEstimte = valueEstimate.cpu().detach().numpy().reshape(1)
            Gt += lmbd**n * (discountedRewards + (discountFactor**n) * valueEstimate)
        else:
            Gt += (lmbd**n) * discountedRewards
    Gt = (1-lmbd)*Gt
    state = sampleTuples[tupleIX]['state']
    #print(tupleIX, Gt)
    return Gt, state, sampleTuples[tupleIX]['action']
    
def computeTDBatch(sampleTuples, lmbd=0.95, tupleIX=None):
    if tupleIX is None:
        tupleIX = np.arange(len(sampleTuples))
    L = len(tupleIX)
    Gts = torch.zeros((L, 1))
    states = np.zeros((L, 16))
    actions = np.zeros((L, 4))
    for l in range(L):
        Gt, state, action = computeTD(sampleTuples, lmbd, tupleIX[l])
        Gts[l] = Gt
        states[l] = state
        actions[l] = action
    return Gts, states, actions

def clipLoss(policy, oldpolicy, state, action, advantage, delta=0.1, eps=0.1):
    amu = action - policy(state)
    siginv = 1/delta*torch.eye(4)
    prob = torch.exp(-0.5*torch.diag(amu@siginv@amu.T))
    
    oldamu = (action - oldpolicy(state)).detach()
    oldprob = torch.exp(-0.5*torch.diag(oldamu@siginv@oldamu.T))
    wi = prob/oldprob
    output = -torch.mean(torch.min(wi*advantage, torch.clamp(wi, 1-eps, 1+eps)*advantage))
    return output

def GaussianProbability(x, mean, cov):
    '''
    computes the probability for a Gaussian distribution with mean and a diagonal
    covariance matrix with a single value, cov, along the diagonal.
    
    Parameters
    ----------
    x : TPPE torch tensor having shape [4, N], where N is the number of samples 
    or batch size that we are considering
        DESCRIPTION represents an action
    mean : TYPE torch tensor with shape [4, N], where N is the number of samples 
    or batch size that we are considering
        DESCRIPTION is the output of the policy network for a given state 
        corresponding to the  mean action.
    cov : TYPE float
        DESCRIPTION diagonal value of the covariance matrix

    Returns
    -------
    actionProbability: torch tensor with shape (1,1) representing the probability
    of action a being played under policy from the given state

    '''
    dim = x.shape[0]     # action space dimension is 4
    # exponent is off by 1/cov
    sigma = torch.eye(dim).double()
    sigma = sigma/cov
    coef = (2*np.pi)**(-dim/2.0) * (cov**dim)**(-1/2)
    mx = x-mean
    gausExp = torch.exp(-mx.t() @ sigma @ mx/2)
    actionProbability = coef * gausExp
    actionProbability = torch.diag(actionProbability)
    return actionProbability

#def probOfAction(action, state, policy):
    
def updatePolicy(actionHistory, stateHistory, advantageHistory, policyNetwork):
    '''
    compute the gradients for the policy network using the PPO loss, must call optimizer.zero_grad()
    and optimizer.step() before and after this function, as this function does not call the optimizer.
    
    Parameters
    ----------
    actionHistory : TYPE numpy array having shape [N, 4], where N is the number of timesteps 
    in the last episode
        DESCRIPTION represents action taken at every timestep in preceeding episdoe
        
    stateHistory : TYPE numpy array with shape [N, 16], where N is the number of time 
    steps in the past episode
        DESCRIPTION contains the state of the agent+environment at everytimestep of 
        previous episode
    advantageHistory : TYPE torch tensor with shape [N, 1]
        DESCRIPTION value of advantage function at everytime step N of previous episode
    
    policyNetwork: torch nn object used to estiamte policy

    Returns
    -------
    none.

    '''
    actionHistory = torch.from_numpy(actionHist).t()
    actionMean = policyNetwork(stateHistory).t()
    actionProbabilities = GaussianProbability(actionHistory, actionMean, 0.1)
    unclippedPPO = -actionProbabilities @ advantageHistory.double()
    eps = policyNetwork.epsilon
    unclippedPPO.backward()
    
    # currently I am not using the clipped loss, to do so just uncomment next line
    #PPOloss = torch.min(actionProbabilities @ advantageHistory.double(), \
    #          torch.clamp(actionProbabilities, 1-eps, 1+eps)@advantageHistory.double())
    #PPOloss.backward()
    #unclippedPPO.backward()
    

# define some values
NUM_EPISODES = 300          # number of episodes we will train on
lr = 1e-3                  # learning rate for Q-learning
discountFactor = 0.95      # discount factor
delta = 0.1                # single-dimension standard deviation of additive action noise
epsilon = 0.1

# create the environment
env = gym.make('FetchReach-v1')
# create policy and value networks
policy = policyNet().to(device)
value = valueNet().to(device)


# MSE loss is used for value network
valueLoss = nn.MSELoss()
# SGD is used for optimization of value network
valueOptimizer = optim.SGD(value.parameters(), lr=lr)
policyOptimizer = optim.SGD(policy.parameters(), lr=lr)

#####
#used for debugging
TD_targs = []
valHist = []
#####

currEpisodeNum = 0                           # initialize episode counter
MAX_TIME_STEPS = env._max_episode_steps      # how many data tuples to store
SIZE_OF_DATA = MAX_TIME_STEPS                # same variable, different name, no good reason why
D = np.empty((SIZE_OF_DATA), dtype=list)     # holds the episode tuples
currTimeStep = 0

finalDist = []
testvec = np.random.randn(1, 16)
testvechist = []
Xhist = []
targetHist = []
valueHist = []

t0 = time.time()
for currEpisodeNum in range(NUM_EPISODES):
    obs = env.reset()
    #env.env.distance_threshold = 0.2              # determines how hard training is
    targetOveride = np.array((.5, 0.5, 0.5))
    targetPos = setTargetPosition(env, targetOveride)
    done = False
    
    D = np.empty((SIZE_OF_DATA), dtype=list)
    
    X = np.zeros((MAX_TIME_STEPS, 3))
    Vel = np.zeros((MAX_TIME_STEPS, 3))
    stateHist = np.zeros((MAX_TIME_STEPS, 16))
    actionHist = np.zeros((MAX_TIME_STEPS, 4))
    for currTimeStep in range(MAX_TIME_STEPS):
        env.render()
        old_obs = obs
        X[currTimeStep] = obs['observation'][0:3]
        action = policy(getFeatureVector(obs))
        action = action + delta*torch.randn(4, device=device)
        action = action.cpu().detach().numpy().reshape(4)
        
        actionHist[currTimeStep] = action
        obs, reward, done, info = env.step(action)
        if reward == 0:
            done = True    # terminates episode when you reach target
        Vel[currTimeStep] = obs['observation'][0:3] - X[currTimeStep]

        ### direction reward  -- Brandon commented this out just for the sake of debuging the training without any aditional rewards
        vel = Vel[currTimeStep]
        direction = targetPos - obs['achieved_goal']
        direction /= np.linalg.norm(direction)
        #reward += np.dot(vel, direction)/np.linalg.norm(vel)

        D[currTimeStep] = {'state' : getFeatureVector(old_obs), 'next_state': getFeatureVector(obs), 
                           'action' : action, 'reward' : reward}
        if done:
            D = D[0:currTimeStep+1]
            actionHist = actionHist[0:currTimeStep+1,:]
            print("Completed episode #:", currEpisodeNum, "........... in", currTimeStep, "timesteps")
            print("action mean:", action)
            break
    #
    done = False
    
    TD_target, state, actionPlayed = computeTDBatch(D)
    valueEstimate = value(state)
    valueHist.append(valueEstimate.detach().numpy())
    #print(TD_target.shape, valueEstimate.shape)
    loss = valueLoss(TD_target, valueEstimate)
    
    valueOptimizer.zero_grad()
    loss.backward()
    valueOptimizer.step()
    
    TD_targs.append(TD_target.detach().numpy())
    valHist.append(valueEstimate.detach().numpy())
    Xhist.append(X)
    targetHist.append(targetPos)
    
    # update the policy network
    advantage = (TD_target - valueEstimate).detach()
    policyOptimizer.zero_grad()
    updatePolicy(actionHist, state, advantage, policy)
    policyOptimizer.step()
    
    finalDist.append(np.sqrt(np.sum((obs['achieved_goal'] - obs['desired_goal'])**2)))
    
    testvecpol = torch.norm(policy(testvec)).item()
    #print(currEpisodeNum, np.round(testvecpol, 3), np.round(finalDist[-1], 3))
    print("current episode:", currEpisodeNum, "final distance from the target:", np.round(finalDist[-1], 3))
    testvechist.append(testvecpol)
    pass

datadict = {}
datadict['valHist'] = valHist
datadict['Xhist'] = Xhist
datadict['targetHist'] = targetHist
datadict['TD_targs'] = TD_targs
datadict['finalDist'] = finalDist
datadict['train_time'] = time.time() - t0
datadict['testvechist'] = testvechist
datadict['valueHist'] = valueHist
sio.savemat('data_' + str(NUM_EPISODES) + 'iter.mat', datadict)

